### ISSUE TITLE
Enrichment for one position and one amino acid

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/Finkle-PHYS-479#8] opened 2022-04-13 15:02 UTC
Write a method that will calculate enrichment and deficiency p-values on the given ranked sequences, for a given amino acid (aa) and for a given position. The count of the aa on that position will also be given, so these values can be calculated with a single pass over the sequences.

Inputs:
    - Ranked sequences
    - The letter for the aa of interest
    - The position of interest
    - The count of the aa on that position 
Outputs:
    - The most significant enrichment p-value
    - The most significant deficiency p-value

**Comment by AdamFinkleUMB** [comment] 2022-04-13 17:10
I don't know how to calculate that value or even fully understand the assignment: do you want to know the p-value of the sequence that has the greatest p-value and has the letter at the position and the p-value of the sequence that has the least p-value that lacks the letter at the position?

**Comment by ozgunbabur** [comment] 2022-04-13 17:15
Do you remember the slide where we discussed how to use a moving threshold to calculate enrichment on a ranked sequence? so this is about that. Your selection threshold will start from the top of the list and move downwards as you calculate the p-values. You will return the most significant enrichment and deficiency p-values. We can talk if that is not clear.

**Comment by AdamFinkleUMB** [comment] 2022-04-13 17:42
I remember that slide but not its details.   Would you please email me it?

**Comment by ozgunbabur** [comment] 2022-04-13 18:44
Here: https://docs.google.com/presentation/d/1ycjs3BdIcXiQz7uCx9KUWYRa9cgc0Ur-CP0R94qRy30/edit?usp=sharing

It is on slide 13.

**Comment by AdamFinkleUMB** [comment] 2022-04-18 23:04
Where is the 'right' answer for the test of this function?

**Comment by ozgunbabur** [comment] 2022-04-19 13:42
We don't have it. This is the first time it will be implemented. 

I am working on a simulated dataset. We can use it to see if the whole code works as expected. Will send it to you once I have it.

**Comment by nurith** [comment] 2022-04-19 15:34
Hi,

Do you know how to create a python application through "actions" so we can run it on the github? (Unless I missed something).
________________________________

**Comment by AdamFinkleUMB** [comment] 2022-04-19 17:20
I can create a GitHub action to run a test every time I push a commit.

**Comment by AdamFinkleUMB** [comment] 2022-04-19 19:23
Thank you!

**Comment by AdamFinkleUMB** [comment] 2022-04-21 19:50
Good news: it runs.
Bad news: it returns zero correlation.

**Comment by AdamFinkleUMB** [comment] 2022-04-21 19:53
Fixed one bug: it returns a correlation of 0.05931568678153657

**Comment by AdamFinkleUMB** [comment] 2022-04-21 20:21
New problem: fisher_exact is designed to return only positive p-values even when set to "less".  Telling the algorithm seek the p-value with the least absolute value instead of the greatest negative value returns almost the same result for both cases.  0.05931568678153656, 0.05931568678153657

**Comment by AdamFinkleUMB** [comment] 2022-04-21 20:29
Got a nice pair of p-values for window 4, column 2, letter "L"

0.0005749521216289109, 0.0005749521216288761

**Comment by AdamFinkleUMB** [comment] 2022-04-21 20:46
Running it for several letters:
A (0.04482498492583142, 0.04482498492583142)
C (0.1078826188446468, 0.10788261884463204)
D (0.09330390539123246, 0.09330390539123246)
E (0.11945687145474417, 0.11945687145474417)
F (0.07707321986110356, 0.07707321986110356)
G (0.00031404775560316096, 0.0003140477556032315)
H (0.1193882037324361, 0.1193882037324361)
I (0.011202272519454742, 0.011202272519454742)

**Comment by AdamFinkleUMB** [comment] 2022-04-21 20:49
The Python code I wrote is lightning fast, as I am sure the Python/C/C++/Fortran is, but calling fisher_stats so many times makes the processor chug.  Multi-processing would improve performance by a factor of cores used.

**Comment by AdamFinkleUMB** [comment] 2022-04-21 22:43
Update: restricting the thresholds to the halfway point yields the same result for the enrichment p-value but a different one for the deficiency p-value.
`
letter, window, index = "L", 4, 2
                                               Deficiency                      Enrichment
limited threshold      0.04062261486280025     0.0005749521216288761
unlimited threshold  0.0005749521216289109 0.0005749521216288761
`

**Comment by AdamFinkleUMB** [comment] 2022-04-21 23:31
I got a 10x speedup, from ~30 seconds per letter per column to ~3 seconds per letter per column, by limiting the thresholds to the midway point and requiring a step size of 4 between fisher_exact calls, which did not significantly change the p-value.  For a small but substantial accuracy sacrifice, the step size can be doubled again.

**Comment by ozgunbabur** [comment] 2022-04-22 02:41
Adam, are you also doing the 20 --> 11 mapping of the amino acids? I used this reduction while preparing the simulated dataset, so you should use it too.

The embedded pattern has a window size of 5. 

I didn't understand the results that you posted 6 hrs ago. Are these all for +2 position?

**Comment by AdamFinkleUMB** [comment] 2022-04-22 03:31
I didn't map the amino acids before, but I have edited the code to do so, and the twofold speedup is nice!  I have also now adjusted the window size to five.  Yes, they were all for the +2 position.

**Comment by ozgunbabur** [comment] 2022-04-25 19:03
That result looks interesting! It has one value that I was hoping to see, but also several other values that I didn't. Can you please focus on enrichment and deficiency of P on +1? Both values are 0.000, which doesn't make sense. When one value is very significant, then we expect the other value to be insignificant. Both of them being very small numbers indicates there is a bug somewhere. You can start by looking at the 2x2 table values for P at +1, and verify the enrichment and deficiency p-values.

**Comment by AdamFinkleUMB** [comment] 2022-04-28 16:49
Column
Letter
(deficiency) best_threshold table p_value confirmed_p_value
(enrichment) best_threshold table p_value confirmed_p_value

-1
A
20 [[23101, 21], [3727, 0]] 0.04330071700623769 0.04330071700623769
4 [[23119, 3], [3725, 2]] 0.14454383637666984 0.14454383637666984
C
3104 [[23374, 3065], [370, 40]] 0.1400655964226241 0.1400655964226241
328 [[26119, 320], [401, 9]] 0.06695101660581776 0.06695101660581776
D
192 [[23028, 177], [3628, 16]] 0.016003114367004564 0.016003114367004564
8512 [[15929, 7276], [2407, 1237]] 0.0009957585357733667 0.0009957585357733667
F
1532 [[24078, 1460], [1238, 73]] 0.4406239445888926 0.4406239445888926
9832 [[16207, 9331], [809, 502]] 0.1047941461247692 0.1047941461247692
H
6152 [[20207, 6039], [489, 114]] 0.009076999048076462 0.009076999048076462
2832 [[23493, 2753], [523, 80]] 0.01898129165472696 0.01898129165472696
I
5568 [[16942, 4506], [4338, 1063]] 0.01619149406716551 0.01619149406716551
1780 [[20051, 1397], [5017, 384]] 0.062213652883405704 0.062213652883405704
K
3132 [[20772, 2765], [2944, 368]] 0.14925816676694786 0.14925816676694786
7028 [[17409, 6128], [2411, 901]] 0.07946246399034185 0.07946246399034185
P
12868 [[12962, 11999], [1018, 870]] 0.04988400418805146 0.04988400418805146
12544 [[13347, 11614], [957, 931]] 0.010407560939540626 0.010407560939540626
Q
7568 [[17586, 6920], [1694, 649]] 0.29899044572487793 0.29899044572487793
172 [[24355, 151], [2321, 22]] 0.04735392370046833 0.04735392370046833
S
156 [[22752, 142], [3940, 15]] 0.03707792512186669 0.03707792512186669
0 [[22894, 0], [3954, 1]] 0.14730530001574202 0.14730530001574202
W
1260 [[25341, 1253], [247, 8]] 0.14906844717296105 0.14906844717296105
2984 [[23639, 2955], [225, 30]] 0.39968661628793734 0.39968661628793734

1
A
16 [[23221, 17], [3611, 0]] 0.08575486356901041 0.08575486356901041
136 [[23129, 109], [3583, 28]] 0.014787512839119842 0.014787512839119842
C
4216 [[22253, 4161], [379, 56]] 0.055396451638383554 0.055396451638383554
10788 [[15814, 10600], [246, 189]] 0.08876050449584842 0.08876050449584842
D
13416 [[11569, 11623], [1863, 1794]] 0.12029071412299319 0.12029071412299319
5948 [[18113, 5079], [2787, 870]] 0.005842618202355628 0.005842618202355628
F
444 [[25010, 427], [1394, 18]] 0.14572545805929032 0.14572545805929032
12 [[25426, 11], [1410, 2]] 0.14700647681656326 0.14700647681656326
H
840 [[25362, 828], [646, 13]] 0.04603113783154998 0.04603113783154998
13208 [[13305, 12885], [335, 324]] 0.5222718606900206 0.5222718606900206
I
11764 [[12005, 9464], [3079, 2301]] 0.04265830050768079 0.04265830050768079
13404 [[10788, 10681], [2656, 2724]] 0.12700589527337972 0.12700589527337972
K
44 [[23418, 42], [3386, 3]] 0.16340741854111318 0.16340741854111318
0 [[23460, 0], [3388, 1]] 0.12622444039229438 0.12622444039229438
P
3500 [[21625, 3306], [1723, 195]] 3.807790723760836e-05 3.807790723760836e-05
68 [[24881, 50], [1899, 19]] 2.230484694720406e-07 2.230484694720406e-07
Q
52 [[24525, 51], [2271, 2]] 0.16251620863178573 0.16251620863178573
232 [[24362, 214], [2254, 19]] 0.6024254639993966 0.6024254639993966
S
20 [[22965, 20], [3863, 1]] 0.1732585697265695 0.1732585697265695
680 [[22406, 579], [3762, 102]] 0.34574539166394175 0.34574539166394175
W
8164 [[18492, 8106], [192, 59]] 0.009008711934625312 0.009008711934625312
5396 [[21274, 5324], [178, 73]] 0.00040962665069523225 0.00040962665069523225

**Comment by AdamFinkleUMB** [comment] 2022-04-28 17:33
Turns out that I had misunderstood the configuration--it works as intended once that was corrected!

**Closed by AdamFinkleUMB** 2022-04-28 17:33 UTC
